Doctorlogic
MaksKuchuk/backend-hospital pull request #3
Opened 2022-10-16 14:22 UTC by MaksKuchuk

2022-10-16 14:28 UTC, Dezzelshipc approved these changes

2022-10-20 11:33 UTC, Vixorem requested changes

2022-10-20 11:33 UTC, Vixorem commented on Infrastructure/Hospital.Persistence/UseCases/AppointmentService.cs
> +    public Result<List<Appointment>> GetAll(Specialization specialization)
Надо возвращать свободные даты. А тут объект класса, но что в нем будет? Ведь прием еще не назначен

2022-11-03 09:43 UTC, Vixorem commented on Infrastructure/Hospital.Persistence/UseCases/AppointmentService.cs
> +    public Result<List<DateTime>> GetAll(Specialization specialization)
Не, погодь, я был не прав, тут ты правильно возвращал аппойнтменты. Но у тебя нет еще одного метода - для получения свободных дат. Вот там нужны дэйттайм. Я думал что этот метод он и есть

2022-11-04 03:18 UTC, Vixorem approved these changes

2022-11-06 13:40 UTC, merged