Jwt token async controllers
MaksKuchuk/backend-hospital pull request #6
Opened 2023-01-21 16:47 UTC by MaksKuchuk

2023-01-22 02:06 UTC, Dezzelshipc approved these changes

2023-01-22 08:49 UTC, Vixorem requested changes

2023-01-22 08:49 UTC, Vixorem commented on Infrastructure/Hospital.Persistence/UseCases/AppointmentService.cs
У вас ПР называется jwt+async, а тут вместо асинк - мютексы. Но да ладно, суть в том, что это не заработает. Если прилетит два параллельных запроса, то это создаст два инстанса этого класса, что, в свою очередь создаст два инстанса этого поля со словарем, и поэтому блокировка не сработает

2023-01-23 09:41 UTC, Vixorem approved these changes

2023-01-23 09:41 UTC, Vixorem commented on Infrastructure/Hospital.Persistence/UseCases/MutexSingleton.cs
> +public class MutexSingleton
Неплохо, но можно было сделать проще) можно быьь просто поле со словарем сделать static)

2023-01-23 11:32 UTC, merged